version: '3.9'

services: 
    
    mysql-development:
        restart: always
        image: mysql:8.0.17
        environment: 
            MYSQL_ROOT_PASSWORD: snowflake6365stark
            MYSQL_DATABASE: dp_sp
        ports:
            - '3309:3306'
        expose:
            - '3306'
        #creates a volume on the host that is outside the container
        volumes:
            - mysql-data:/var/lib/mysql
    data:
        image: mysql:8.0.17
        volumes: 
            - mysql-data:/var/lib/mysql
        command: 'true'
    web:
        build: .
        ports:
            - "5000:5000"
    redis:
        image: "redis:alpine"

volumes:
    mysql-data:
